### ISSUE TITLE
Technical typo in Section 6.6 Mutable State

### ISSUE THREAD

**Issue by wrenna-robson** [blanchette/logical_verification_2021#3]
At the bottom of pg 104 in the standard pdf and on page 151 of the tablet version, the following text appears:

> The read operation simply returns the current state s (in the first pair component)
> and leaves the state unchanged (in the second pair component). The write operation
> replaces the state s with t and returns (). The pure operation returns
> the current state s unchanged tupled together with the given value a. The bind
> operation passes the initial state to the f argument, yielding a result a and a new
> state t. These are passed to g, which returns a new result and a new state.

However, in the code above it (screenshotted here), the relevant arguments are ma and f, not f and g. I believe - to match the "faction" equivalent code - they should indeed be f and g. 
![image](https://user-images.githubusercontent.com/34025592/142079388-dbb5c58c-a875-43b9-af80-c28356343c2c.png)

This would also require a change in love06_moands_demo.lean.

**Comment by blanchette** [comment]
Thanks for the report. This should be fixed in the 2022 edition of the book.
